services:
  postgres:
    image: postgres:16
    container_name: rikale-postgres
    restart: always
    environment:
      POSTGRES_USER: rikale
      POSTGRES_PASSWORD: rikale
      POSTGRES_DB: rikale
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
